env: "local"

postgres:
  storage_path: "host=postgres-auth port=5432 user=postgres password=postgres_1234 dbname=Authentication sslmode=disable"

auth:
  secret_key: "E3IiecHXTaBytd5Sik50L/YvQTVlzmngF8u6TR+N66w"
  access_token_ttl: 15m
  refresh_token_ttl: 168h

grpc:
  port: 9090
  

kafka:
  broker: "kafka:9092"
  topic: "emails"

redis:
  addr: "redis:6379"
